version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
