openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: Express API for managing TODOs

paths:
  /todos:
    get:
      summary: Get all tasks
      responses:
        200:
          description: A list of TODOs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        201:
          description: New task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        400:
          description: Invalid input

  /todos/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the task
          schema:
            type: string
      responses:
        200:
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        404:
          description: Task not found
    patch:
      summary: Update a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the task
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        200:
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        400:
          description: Invalid input
        404:
          description: Task not found
    delete:
      summary: Delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: Unique ID of the task
          schema:
            type: string
      responses:
        200:
          description: Task deleted
        404:
          description: Task not found

components:
  schemas:
    ToDo:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, in progress, completed]
